# .goreleaser.yml
project_name: shellspy
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "shellspy"
    dir: .
    main: ./cmd/shellspy/main.go

